name: API Key Replacement

on:
  push:
    branches:
      - secret

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace API key
        run: |
          sed -i 's/API_KEY_PLACEHOLDER/${{ secrets.APPKEY }}/g' 'js/tfl.js'

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Replace API key"
