on:
  issues:
    types: [opened]
jobs:
  Add_New_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
      - name: Add new issue to project
        uses: carlosbuitragosan/api/.github/workflows/new-issue.yml@main
        with:
          action-token: ${{ secrets.GITHUB_TOKEN }}
          project-url: "https://github.com/users/carlosbuitragosan/projects/3"
          column-name: "New"
