on:
  issues:
    types: [opened]
jobs:
  Add_New_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
    - uses: carlosbuitragosan/api/.github/workflows/new-issue.yml@develop
      with:
        action-token: "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"
        project-url: "https://github.com/users/carlosbuitragosan/projects/3"
        column-name: "New"
