name: Automate Issue Creation

on:
  issues:
    types:
      - opened

jobs:
  automate-issue-creation:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to project board
        uses: github/scripts-to-rule-them-all@v2
        with:
          script: issue-to-project-board
        env:
          PROJECT_COLUMN_NAME: New
